# Generated by Django 6.0.2 on 2026-05-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
